export interface City {
  slug: string
  name: string
  state: string
  region: string
  nearCities: string
  demanda: string
  diferencial: string
  lat: number
  lng: number
}

export const cities: City[] = [
  {
    slug: "itumbiara",
    name: "Itumbiara",
    state: "GO",
    region: "sul de Goiás",
    nearCities: "Araporã, Centralina e Morrinhos",
    demanda: "empresas, indústrias, condomínios e supermercados",
    diferencial: "Somos fabricantes locais em Itumbiara — prazo menor e sem frete de longa distância para a região.",
    lat: -18.4186,
    lng: -49.2155,
  },
  {
    slug: "arapora",
    name: "Araporã",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Itumbiara e Centralina",
    demanda: "empresas e residências da região do Paranaíba",
    diferencial: "Entregamos em Araporã em até 1 dia útil a partir da nossa fábrica em Itumbiara.",
    lat: -18.4408,
    lng: -49.1669,
  },
  {
    slug: "morrinhos",
    name: "Morrinhos",
    state: "GO",
    region: "sul de Goiás",
    nearCities: "Caldas Novas e Goiatuba",
    demanda: "empresas, supermercados e condomínios",
    diferencial: "Atendemos Morrinhos com entrega rápida e orçamento personalizado via WhatsApp.",
    lat: -17.7333,
    lng: -49.1,
  },
  {
    slug: "goiatuba",
    name: "Goiatuba",
    state: "GO",
    region: "sul de Goiás",
    nearCities: "Morrinhos e Caldas Novas",
    demanda: "empresas do agronegócio, comércio local e condomínios",
    diferencial: "Capachos industriais para fazendas e empresas do agronegócio de Goiatuba.",
    lat: -18.0136,
    lng: -49.3613,
  },
  {
    slug: "centralina",
    name: "Centralina",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Itumbiara e Araporã",
    demanda: "empresas e residências",
    diferencial: "Fabricante mais próximo de Centralina — entrega em 1 dia útil.",
    lat: -18.5836,
    lng: -49.1933,
  },
  {
    slug: "caldas-novas",
    name: "Caldas Novas",
    state: "GO",
    region: "sudeste de Goiás",
    nearCities: "Morrinhos e Rio Quente",
    demanda: "hotéis, pousadas, centros turísticos, SPAs e resorts",
    diferencial: "Capachos para hotelaria e turismo — identidade visual para entrada de hotéis e pousadas de Caldas Novas.",
    lat: -17.7394,
    lng: -48.6253,
  },
  {
    slug: "rio-verde",
    name: "Rio Verde",
    state: "GO",
    region: "sudoeste de Goiás",
    nearCities: "Jataí e Santa Helena",
    demanda: "empresas do agronegócio, cooperativas e comércio",
    diferencial: "Capachos personalizados para Rio Verde com entrega em 5 dias úteis.",
    lat: -17.8159,
    lng: -50.9192,
  },
  {
    slug: "goiania",
    name: "Goiânia",
    state: "GO",
    region: "centro de Goiás",
    nearCities: "Aparecida de Goiânia e Senador Canedo",
    demanda: "empresas, condomínios, clínicas, shopping centers e hospitais",
    diferencial: "Fabricante direto em Goiás — sem intermediários, entregamos em Goiânia com preço de fábrica.",
    lat: -16.6869,
    lng: -49.2648,
  },
  // GOIÁS — cidades adicionais
  {
    slug: "anapolis",
    name: "Anápolis",
    state: "GO",
    region: "centro-norte de Goiás",
    nearCities: "Goiânia e Brasília",
    demanda: "empresas farmacêuticas, indústrias e comércio",
    diferencial: "Polo industrial e agroindustrial — entregamos em Anápolis em 3 dias úteis.",
    lat: -16.3281,
    lng: -48.9528,
  },
  {
    slug: "aparecida-de-goiania",
    name: "Aparecida de Goiânia",
    state: "GO",
    region: "região metropolitana de Goiânia",
    nearCities: "Goiânia e Trindade",
    demanda: "empresas, condomínios e comércio da região metropolitana",
    diferencial: "Fabricante próximo em Goiás — entrega rápida para toda a região metropolitana.",
    lat: -16.8204,
    lng: -49.2453,
  },
  {
    slug: "luziania",
    name: "Luziânia",
    state: "GO",
    region: "entorno do Distrito Federal",
    nearCities: "Brasília e Valparaíso de Goiás",
    demanda: "empresas, condomínios e comércio do entorno do DF",
    diferencial: "Entregamos em Luziânia em até 3 dias úteis, com preço de fábrica.",
    lat: -16.2524,
    lng: -47.9504,
  },
  {
    slug: "valparaiso-de-goias",
    name: "Valparaíso de Goiás",
    state: "GO",
    region: "entorno do Distrito Federal",
    nearCities: "Brasília e Luziânia",
    demanda: "empresas, condomínios e residências do entorno do DF",
    diferencial: "Capachos personalizados para Valparaíso de Goiás — entrega em 3 dias úteis.",
    lat: -16.0732,
    lng: -47.9742,
  },
  {
    slug: "trindade",
    name: "Trindade",
    state: "GO",
    region: "região metropolitana de Goiânia",
    nearCities: "Goiânia e Aparecida de Goiânia",
    demanda: "empresas, comércio local e condomínios",
    diferencial: "Entregamos em Trindade com prazo garantido dentro da região metropolitana.",
    lat: -16.6514,
    lng: -49.4869,
  },
  {
    slug: "senador-canedo",
    name: "Senador Canedo",
    state: "GO",
    region: "região metropolitana de Goiânia",
    nearCities: "Goiânia e Goiânia",
    demanda: "indústrias, empresas e condomínios",
    diferencial: "Polo industrial próximo a Goiânia — entrega rápida para Senador Canedo.",
    lat: -16.7058,
    lng: -49.0923,
  },
  {
    slug: "pirenopolis",
    name: "Pirenópolis",
    state: "GO",
    region: "centro de Goiás",
    nearCities: "Anápolis e Goiânia",
    demanda: "pousadas, restaurantes, lojas e hotéis do turismo",
    diferencial: "Capachos personalizados para o turismo de Pirenópolis — identidade visual para sua pousada ou restaurante.",
    lat: -15.8508,
    lng: -48.9591,
  },
  {
    slug: "cristalina",
    name: "Cristalina",
    state: "GO",
    region: "sudeste de Goiás",
    nearCities: "Brasília e Luziânia",
    demanda: "empresas do agronegócio e pedras ornamentais",
    diferencial: "Capachos personalizados para Cristalina com entrega em 4 dias úteis.",
    lat: -16.7686,
    lng: -47.6143,
  },
  {
    slug: "catalao",
    name: "Catalão",
    state: "GO",
    region: "sudeste de Goiás",
    nearCities: "Uberlândia e Itumbiara",
    demanda: "mineradoras, montadoras e empresas industriais",
    diferencial: "Capachos para o polo industrial de Catalão, com entrega em até 4 dias úteis.",
    lat: -18.1664,
    lng: -47.9475,
  },
  {
    slug: "jatai",
    name: "Jataí",
    state: "GO",
    region: "sudoeste de Goiás",
    nearCities: "Rio Verde e Mineiros",
    demanda: "empresas do agronegócio, cooperativas e comércio",
    diferencial: "Capachos para o agronegócio de Jataí com entrega em até 5 dias úteis.",
    lat: -17.8803,
    lng: -51.7128,
  },
  {
    slug: "mineiros",
    name: "Mineiros",
    state: "GO",
    region: "sudoeste de Goiás",
    nearCities: "Jataí e Rio Verde",
    demanda: "empresas do agronegócio e comércio local",
    diferencial: "Capachos personalizados para Mineiros com entrega em até 5 dias úteis.",
    lat: -17.5691,
    lng: -52.5523,
  },
  {
    slug: "formosa",
    name: "Formosa",
    state: "GO",
    region: "nordeste de Goiás",
    nearCities: "Brasília e Planaltina",
    demanda: "empresas, comércio e condomínios do entorno do DF",
    diferencial: "Entrega em Formosa em até 3 dias úteis — próximo a Brasília.",
    lat: -15.5318,
    lng: -47.3355,
  },
  // MINAS GERAIS — cidades adicionais
  {
    slug: "uberlandia",
    name: "Uberlândia",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Uberaba e Araguari",
    demanda: "empresas, clínicas, hospitais, shopping centers e indústrias",
    diferencial: "Maior cidade do Triângulo Mineiro — entregamos em Uberlândia em 2 dias úteis.",
    lat: -18.9186,
    lng: -48.2772,
  },
  {
    slug: "uberaba",
    name: "Uberaba",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Uberlândia e Araxá",
    demanda: "empresas do agronegócio, universidades e clínicas",
    diferencial: "Capachos personalizados para Uberaba com entrega em 2 dias úteis.",
    lat: -19.7483,
    lng: -47.9317,
  },
  {
    slug: "ituiutaba",
    name: "Ituiutaba",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Uberlândia e Itumbiara",
    demanda: "empresas, comércio e universidades",
    diferencial: "Entregamos em Ituiutaba em até 2 dias úteis a partir de Itumbiara.",
    lat: -18.9717,
    lng: -49.4647,
  },
  {
    slug: "araxa",
    name: "Araxá",
    state: "MG",
    region: "Alto Paranaíba",
    nearCities: "Uberaba e Patos de Minas",
    demanda: "mineradoras, hotéis termais, empresas e resorts",
    diferencial: "Capachos para o polo mineral e turístico de Araxá, com entrega em 3 dias úteis.",
    lat: -19.5928,
    lng: -46.9406,
  },
  {
    slug: "patos-de-minas",
    name: "Patos de Minas",
    state: "MG",
    region: "Alto Paranaíba",
    nearCities: "Araxá e Uberlândia",
    demanda: "empresas, cooperativas e comércio do Alto Paranaíba",
    diferencial: "Entrega em Patos de Minas em até 4 dias úteis.",
    lat: -18.5792,
    lng: -46.5183,
  },
  {
    slug: "divinopolis",
    name: "Divinópolis",
    state: "MG",
    region: "centro-oeste de Minas",
    nearCities: "Sete Lagoas e Itaúna",
    demanda: "empresas de confecção, comércio e hospitais",
    diferencial: "Capachos personalizados para Divinópolis com entrega em 3 dias úteis.",
    lat: -20.1397,
    lng: -44.8836,
  },
  {
    slug: "sete-lagoas",
    name: "Sete Lagoas",
    state: "MG",
    region: "centro de Minas Gerais",
    nearCities: "Belo Horizonte e Divinópolis",
    demanda: "empresas, indústrias e comércio",
    diferencial: "Entregamos em Sete Lagoas em até 3 dias úteis.",
    lat: -19.4658,
    lng: -44.2469,
  },
  {
    slug: "ipatinga",
    name: "Ipatinga",
    state: "MG",
    region: "Vale do Aço",
    nearCities: "Coronel Fabriciano e Timóteo",
    demanda: "siderúrgicas, empresas industriais e comércio",
    diferencial: "Capachos para o polo siderúrgico do Vale do Aço com entrega em 4 dias úteis.",
    lat: -19.4687,
    lng: -42.5372,
  },
  {
    slug: "teofilo-otoni",
    name: "Teófilo Otoni",
    state: "MG",
    region: "nordeste de Minas",
    nearCities: "Governador Valadares e Nanuque",
    demanda: "empresas de pedras preciosas, comércio e hotéis",
    diferencial: "Entregamos em Teófilo Otoni em até 4 dias úteis.",
    lat: -17.8586,
    lng: -41.5047,
  },
  {
    slug: "montes-claros",
    name: "Montes Claros",
    state: "MG",
    region: "norte de Minas",
    nearCities: "Pirapora e Bocaiúva",
    demanda: "empresas, clínicas, hospitais e comércio do norte de Minas",
    diferencial: "Maior cidade do norte de Minas — entregamos em Montes Claros em 4 dias úteis.",
    lat: -16.7286,
    lng: -43.8578,
  },
  {
    slug: "araguari",
    name: "Araguari",
    state: "MG",
    region: "Triângulo Mineiro",
    nearCities: "Uberlândia e Araporã",
    demanda: "empresas, comércio e indústrias do Triângulo Mineiro",
    diferencial: "Entregamos em Araguari em até 2 dias úteis, próximo a Uberlândia.",
    lat: -18.6467,
    lng: -48.1883,
  },
  // SÃO PAULO
  {
    slug: "sao-paulo",
    name: "São Paulo",
    state: "SP",
    region: "Grande São Paulo",
    nearCities: "Campinas e Sorocaba",
    demanda: "empresas, escritórios, shopping centers, clínicas e condomínios",
    diferencial: "Entregamos em São Paulo via transportadora em até 5 dias úteis, com preço de fábrica.",
    lat: -23.5505,
    lng: -46.6333,
  },
  {
    slug: "ribeirao-preto",
    name: "Ribeirão Preto",
    state: "SP",
    region: "nordeste de São Paulo",
    nearCities: "Araraquara e Bauru",
    demanda: "empresas, clínicas médicas, hospitais e shopping centers",
    diferencial: "Capachos personalizados para Ribeirão Preto com entrega em 4 dias úteis.",
    lat: -21.1775,
    lng: -47.8103,
  },
  {
    slug: "sao-jose-do-rio-preto",
    name: "São José do Rio Preto",
    state: "SP",
    region: "noroeste de São Paulo",
    nearCities: "Ribeirão Preto e Bauru",
    demanda: "empresas, comércio, agronegócio e hospitais",
    diferencial: "Entregamos em São José do Rio Preto em até 4 dias úteis.",
    lat: -20.8113,
    lng: -49.3758,
  },
  {
    slug: "araraquara",
    name: "Araraquara",
    state: "SP",
    region: "centro de São Paulo",
    nearCities: "Ribeirão Preto e Bauru",
    demanda: "empresas, indústrias e comércio do interior paulista",
    diferencial: "Capachos personalizados para Araraquara com entrega em 4 dias úteis.",
    lat: -21.7945,
    lng: -48.1756,
  },
  {
    slug: "bauru",
    name: "Bauru",
    state: "SP",
    region: "centro-oeste de São Paulo",
    nearCities: "Araraquara e Marília",
    demanda: "empresas, comércio e universidades do centro-oeste paulista",
    diferencial: "Entregamos em Bauru em até 5 dias úteis.",
    lat: -22.3144,
    lng: -49.0609,
  },
  {
    slug: "marilia",
    name: "Marília",
    state: "SP",
    region: "centro-oeste de São Paulo",
    nearCities: "Bauru e Botucatu",
    demanda: "empresas, indústrias de alimentos e comércio",
    diferencial: "Capachos para o polo industrial de Marília com entrega em 5 dias úteis.",
    lat: -22.2132,
    lng: -49.9458,
  },
  {
    slug: "botucatu",
    name: "Botucatu",
    state: "SP",
    region: "centro de São Paulo",
    nearCities: "Bauru e Sorocaba",
    demanda: "universidades, hospitais, empresas e comércio",
    diferencial: "Entregamos em Botucatu em até 5 dias úteis.",
    lat: -22.8854,
    lng: -48.4447,
  },
  {
    slug: "jau",
    name: "Jaú",
    state: "SP",
    region: "centro de São Paulo",
    nearCities: "Bauru e Araraquara",
    demanda: "empresas de calçados, couro, comércio e indústrias",
    diferencial: "Capachos personalizados para Jaú com entrega em 5 dias úteis.",
    lat: -22.2958,
    lng: -48.5581,
  },
  {
    slug: "itu",
    name: "Itu",
    state: "SP",
    region: "interior de São Paulo",
    nearCities: "Sorocaba e Campinas",
    demanda: "empresas, condomínios e comércio do interior paulista",
    diferencial: "Entregamos em Itu em até 5 dias úteis via transportadora.",
    lat: -23.2638,
    lng: -47.2994,
  },
  {
    slug: "sorocaba",
    name: "Sorocaba",
    state: "SP",
    region: "interior de São Paulo",
    nearCities: "Itu e Botucatu",
    demanda: "empresas, indústrias, condomínios e comércio",
    diferencial: "Capachos para o polo industrial de Sorocaba com entrega em 5 dias úteis.",
    lat: -23.5015,
    lng: -47.4526,
  },
  // MATO GROSSO DO SUL
  {
    slug: "campo-grande",
    name: "Campo Grande",
    state: "MS",
    region: "centro de Mato Grosso do Sul",
    nearCities: "Dourados e Três Lagoas",
    demanda: "empresas, supermercados, condomínios e hospitais",
    diferencial: "Entregamos em Campo Grande em até 4 dias úteis, com capachos de alta qualidade.",
    lat: -20.4697,
    lng: -54.6201,
  },
  {
    slug: "dourados",
    name: "Dourados",
    state: "MS",
    region: "sul de Mato Grosso do Sul",
    nearCities: "Campo Grande e Maracaju",
    demanda: "empresas do agronegócio, cooperativas e comércio",
    diferencial: "Capachos personalizados para Dourados com entrega em 4 dias úteis.",
    lat: -22.2211,
    lng: -54.8114,
  },
  {
    slug: "tres-lagoas",
    name: "Três Lagoas",
    state: "MS",
    region: "leste de Mato Grosso do Sul",
    nearCities: "Campo Grande e Araçatuba",
    demanda: "celulose, indústrias, empresas e comércio",
    diferencial: "Entregamos em Três Lagoas em até 3 dias úteis.",
    lat: -20.7849,
    lng: -51.7018,
  },
  {
    slug: "corumba",
    name: "Corumbá",
    state: "MS",
    region: "oeste de Mato Grosso do Sul",
    nearCities: "Campo Grande e Ladário",
    demanda: "empresas do pantanal, turismo e comércio",
    diferencial: "Capachos personalizados para Corumbá com entrega em até 5 dias úteis.",
    lat: -19.0078,
    lng: -57.6514,
  },
  {
    slug: "maracaju",
    name: "Maracaju",
    state: "MS",
    region: "sul de Mato Grosso do Sul",
    nearCities: "Dourados e Campo Grande",
    demanda: "empresas do agronegócio e comércio local",
    diferencial: "Entregamos em Maracaju em até 4 dias úteis.",
    lat: -21.6144,
    lng: -55.1678,
  },
  // DISTRITO FEDERAL E OUTROS
  {
    slug: "brasilia",
    name: "Brasília",
    state: "DF",
    region: "Distrito Federal",
    nearCities: "Luziânia e Formosa",
    demanda: "órgãos públicos, empresas, condomínios, hospitais e shopping centers",
    diferencial: "Entregamos em Brasília em até 2 dias úteis — fabricante em Goiás, preço de fábrica no DF.",
    lat: -15.7754,
    lng: -47.7979,
  },
  {
    slug: "palmas",
    name: "Palmas",
    state: "TO",
    region: "centro-norte do Tocantins",
    nearCities: "Porto Nacional e Paraíso do Tocantins",
    demanda: "empresas, órgãos públicos e comércio",
    diferencial: "Entregamos em Palmas em até 4 dias úteis via transportadora.",
    lat: -10.2492,
    lng: -48.3243,
  },
  {
    slug: "maringa",
    name: "Maringá",
    state: "PR",
    region: "noroeste do Paraná",
    nearCities: "Londrina e Cascavel",
    demanda: "empresas, condomínios, universidades e comércio",
    diferencial: "Capachos personalizados para Maringá com entrega em até 5 dias úteis.",
    lat: -23.4205,
    lng: -51.9333,
  },
]

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug)
}

export function getAllCitySlugs(): string[] {
  return cities.map((city) => city.slug)
}
